# Generated by Django 3.0.1 on 2020-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursetask_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days_of_week',
            field=models.PositiveIntegerField(default=31, help_text='The days of the week when school is in session'),
        ),
    ]
