# Generated by Django 3.0.2 on 2020-06-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20200605_1549'),
        ('courses', '0003_course_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days_of_week',
            field=models.PositiveIntegerField(default=31, help_text='The days of the week when this runs'),
        ),
        migrations.AlterField(
            model_name='course',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schools.GradeLevel'),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_tasks', to='courses.Course'),
        ),
    ]
