# Generated by Django 3.0.1 on 2020-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_coursework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='completed_date',
            field=models.DateField(db_index=True),
        ),
    ]
