# Generated by Django 3.0.1 on 2020-06-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200419_1716'),
        ('students', '0004_auto_20200418_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursework',
            options={'verbose_name_plural': 'coursework'},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.GradeLevel'),
        ),
    ]
