# Generated by Django 3.0.1 on 2020-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_gradelevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='days_of_week',
            field=models.PositiveIntegerField(default=31, help_text='The days of the week when school is in session'),
        ),
    ]
