# Generated by Django 3.0.1 on 2020-04-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolyear_days_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='schools.SchoolYear'),
        ),
    ]
