# Generated by Django 3.0.2 on 2020-06-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20200419_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='days_of_week',
            field=models.PositiveIntegerField(default=31, help_text='The days of the week when this runs'),
        ),
    ]
